name = "DictTools"
uuid = "6033591e-aae9-4c88-8f5f-a341f9ca5325"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.2.4"

[deps]
# Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
# ZChop = "8603256b-76ad-53fe-b511-38a38e6437cd"

[compat]
# Dictionaries = "0.3"
# ZChop = "0.3"
julia = "1"

[extras]
ReTestItems = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReTestItems"]
