name = "DictTools"
uuid = "6033591e-aae9-4c88-8f5f-a341f9ca5325"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.2.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"

[compat]
julia = "1"
Dictionaries = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
